# Generated by Django 5.0.6 on 2024-11-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_blog_content_alter_service_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='subtitle',
        ),
    ]
