# Generated by Django 5.0.6 on 2024-11-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_blog_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
    ]
